success all tests
itmo-java-basics-2020/task-3-hashtable-classes-inner-classes-class-object-kvestus pull request #1
Opened 2020-03-28 15:34 UTC by kvestus

2020-04-04 13:23 UTC, hey-its-sasha requested changes
называй коммиты продолжением фразы
if applied this commit will

то есть например "implement hashtable" или "fix codestyle"

2020-04-04 13:23 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +        this.threshold = (int) Math.floor(capacity * loadFactor);
нужен floor()?

2020-04-04 13:23 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +        if (this.size == MAX_SIZE) {
везде кроме конструктора можешь не спамить словом this, будет легче читаться

2020-04-04 13:23 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +        return (foundEntry == null) ? null : foundEntry.value;
посмотри что такое java.util.Optional.ofNullable()
по идее идея должна была тебе предложить обернуть в него

2020-04-04 13:23 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static class Entry {
прокатит ли сделать этот класс immutable?

2020-04-04 13:23 UTC, wtf513 commented on src/main/java/ru/itmo/java/HashTable.java
> +        Object oldValue = this.elements[foundIndex].value;
а у тебя же как раз для этого случая написаны геттеры. их и юзай

2020-04-30 08:02 UTC, kvestus commented on src/main/java/ru/itmo/java/HashTable.java
> +        return (foundEntry == null) ? null : foundEntry.value;
В данном случае это не удобно, так как ofNullable() возвращает значение самого элемента, если он существует, а нам необходимо вернуть "value" элемента.
И будет выглядеть не лучше чем это.
Если допустим foundEntry == null и я вызову ofNullable(foundEntry.value), то мы сломаемся.

2020-04-30 08:21 UTC, kvestus commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static class Entry {
В хэш-таблице есть возможность изменять данный по ключу, так что не получится

2020-04-30 08:29 UTC, kvestus commented on src/main/java/ru/itmo/java/HashTable.java
> +    private static class Entry {
Если брать в расчет, что хэш-таблице нет функции изменения значения уже созданного элемента, то можно

2020-04-30 08:32 UTC, merged